# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/usuario/Desktop/PROV_WS/MODULOS_IP/mux81/mux81.srcs/sources_1/bd/mux81/ip/mux81_mux41_ip_v1_0_0_0/mux81_mux41_ip_v1_0_0_0.xci
# IP: The module: 'mux81_mux41_ip_v1_0_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/usuario/Desktop/PROV_WS/MODULOS_IP/mux81/mux81.gen/sources_1/bd/mux81/ip/mux81_mux41_ip_v1_0_0_0/mux41.srcs/sources_1/bd/mux41_ip/ip/mux41_ip_mux21_0_0/mux41_ip_mux21_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mux41_ip_mux21_0_0 || ORIG_REF_NAME==mux41_ip_mux21_0_0} -quiet] -quiet

# IP: c:/Users/usuario/Desktop/PROV_WS/MODULOS_IP/mux81/mux81.gen/sources_1/bd/mux81/ip/mux81_mux41_ip_v1_0_0_0/mux41.srcs/sources_1/bd/mux41_ip/ip/mux41_ip_mux21_0_1/mux41_ip_mux21_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mux41_ip_mux21_0_1 || ORIG_REF_NAME==mux41_ip_mux21_0_1} -quiet] -quiet

# IP: c:/Users/usuario/Desktop/PROV_WS/MODULOS_IP/mux81/mux81.gen/sources_1/bd/mux81/ip/mux81_mux41_ip_v1_0_0_0/mux41.srcs/sources_1/bd/mux41_ip/ip/mux41_ip_mux21_0_2/mux41_ip_mux21_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mux41_ip_mux21_0_2 || ORIG_REF_NAME==mux41_ip_mux21_0_2} -quiet] -quiet

# XDC: c:/Users/usuario/Desktop/PROV_WS/MODULOS_IP/mux81/mux81.gen/sources_1/bd/mux81/ip/mux81_mux41_ip_v1_0_0_0/mux41.gen/sources_1/bd/mux41_ip/mux41_ip_ooc.xdc

# IP: c:/Users/usuario/Desktop/PROV_WS/MODULOS_IP/mux81/mux81.srcs/sources_1/bd/mux81/ip/mux81_mux41_ip_v1_0_0_0/mux81_mux41_ip_v1_0_0_0.xci
# IP: The module: 'mux81_mux41_ip_v1_0_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/usuario/Desktop/PROV_WS/MODULOS_IP/mux81/mux81.gen/sources_1/bd/mux81/ip/mux81_mux41_ip_v1_0_0_0/mux41.srcs/sources_1/bd/mux41_ip/ip/mux41_ip_mux21_0_0/mux41_ip_mux21_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mux41_ip_mux21_0_0 || ORIG_REF_NAME==mux41_ip_mux21_0_0} -quiet] -quiet

# IP: c:/Users/usuario/Desktop/PROV_WS/MODULOS_IP/mux81/mux81.gen/sources_1/bd/mux81/ip/mux81_mux41_ip_v1_0_0_0/mux41.srcs/sources_1/bd/mux41_ip/ip/mux41_ip_mux21_0_1/mux41_ip_mux21_0_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mux41_ip_mux21_0_1 || ORIG_REF_NAME==mux41_ip_mux21_0_1} -quiet] -quiet

# IP: c:/Users/usuario/Desktop/PROV_WS/MODULOS_IP/mux81/mux81.gen/sources_1/bd/mux81/ip/mux81_mux41_ip_v1_0_0_0/mux41.srcs/sources_1/bd/mux41_ip/ip/mux41_ip_mux21_0_2/mux41_ip_mux21_0_2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mux41_ip_mux21_0_2 || ORIG_REF_NAME==mux41_ip_mux21_0_2} -quiet] -quiet

# XDC: c:/Users/usuario/Desktop/PROV_WS/MODULOS_IP/mux81/mux81.gen/sources_1/bd/mux81/ip/mux81_mux41_ip_v1_0_0_0/mux41.gen/sources_1/bd/mux41_ip/mux41_ip_ooc.xdc
