ALTER SESSION SET "_ORACLE_SCRIPT"=true;
CREATE USER CRISTOPHER_VANEGAS IDENTIFIED BY ABCtyu890;
GRANT create session to CRISTOPHER_VANEGAS;

SELECT * FROM ALL_USERS 
            WHERE USERNAME = 'CRISTOPHER_VANEGAS';

SELECT * FROM ALL_USERS;