ALTER SESSION SET "_ORACLE_SCRIPT"=true;
CREATE USER JVERA IDENTIFIED BY abc12345 PASSWORD EXPIRE;

GRANT CREATE SESSION TO JVERA;


SELECT * FROM ALL_USERS;

-- RESET PASSWORD --
ALTER USER JVERA PROFILE default LIMIT PASSWORD_VERIFY_FUNCTION verify_function_name;
ALTER USER JVERA IDENTIFIED BY aaa12345;